//! Time synchronized input and output components for processing devices.
//!
//! A device that generates data should use an `OutputArray`. An output array
//! create a number of output channels to contain frames generated by our device;
//! the device is responsible for pushing new frames into these channels.
//! 
//! A device that receives data should use an `InputArray`. An input array
//! starts with each of its inputs set to `None`. These must be populated with
//! `ChannelRef`s from one or more output arrays before they will return data.
//! 
//! A device may contain both an input and an output component, and use its
//! inputs to generate its outputs.

#![experimental]

pub use self::io_array::{InputArray, OutputArray};
pub use self::io_elements::{InputElement, OutputElement};

pub mod channel;
pub mod io_array;
pub mod io_elements;
