//! Time synchronized input and output components for audio devices.
//!
//! A device that generates audio should use an `OutputArray`. An output array
//! create a number of output channels to contain audio generated by our device;
//! the device is responsible for pushing new audio into these channels.
//! 
//! A device that takes in audio should use an `InputArray`. An input array
//! starts with each of its inputs set to `None`. These must be populated with
//! `ChannelRef`s from one or more output arrays before they will receive input
//! data.
//! 
//! A device may contain both an input and an output component, and use its
//! inputs to generate its outputs.

#![experimental]

pub use self::channel::ChannelRef;
pub use self::io_array::{InputArray, OutputArray};

pub mod channel;
pub mod io_array;
